Repository PodYapolskiy/mydget, pull requests merged in 2023-07, with the labels that each got.

#20 :lipstick: feat: added DaisyUI and logos
  package-lock.json
  package.json
  src/app.html
  src/lib/components/LoginForm.svelte
  src/lib/components/Navbar.svelte
  src/routes/+page.svelte
  src/routes/resetPassword/+page.svelte
  static/logo.png
  static/logoEye.png
  static/logoWithoutSlogan.png
  tailwind.config.js
Labels: Style

#21 :passport_control: added password reset
  src/lib/components/PasswordReset.svelte
  src/routes/passwordResetSent/+page.svelte
  src/routes/passwordResetSent/+page.ts
  src/routes/resetPassword/+page.svelte
Labels: Feature

#24 🔀 feat: google authorization
  src/lib/components/LoginForm.svelte
  src/lib/components/PasswordReset.svelte
  src/routes/passwordResetSent/+page.svelte
  static/GoogleGLogo.svg.png
Labels: Feature

#26 🔀 feat: updated navbar
  .prettierrc
  src/app.css
  src/lib/components/Navbar.svelte
  src/routes/passwordResetSent/+page.svelte
  src/routes/transactions/+page.svelte
  src/routes/transactions/+page.ts
  static/SampleUserIcon.png
  static/favicon.png
Labels: Feature

#27 🔀 feat: google authorization and updated navbar
  src/routes/passwordResetSent/+page.svelte
Labels: Feature

#28 🔀 feat: homepage & footer
  src/lib/components/CommonWords.svelte
  src/lib/components/Footer.svelte
  src/lib/components/Team.svelte
  src/lib/components/TechnologicalStack.svelte
  src/lib/components/Welcome.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  static/anatolii.jpg
  static/benedict.jpg
  static/dprost.jpg
  static/ebob.jpg
  static/igolov.jpg
  static/skuzmich.jpg
Labels: Feature

#36 🍻 feat: creation user after registration
  .gitignore
  src/lib/components/LoginForm.svelte
  src/routes/fb.ts
  src/routes/transactions/+page.svelte
Labels: Feature

#38 🔨 build: add check to husky
  .husky/pre-commit
  package.json
Labels: Dev

#47 Feat/about page
  src/lib/components/Footer.svelte
  src/lib/components/Team.svelte
  src/lib/components/TechnologicalStack.svelte
  src/lib/components/Welcome.svelte
  src/lib/images/about_img/anatolii.jpg
  src/lib/images/about_img/logo.svg
  src/lib/images/footer_img/email.png
  src/lib/images/footer_img/github.svg
  src/lib/images/footer_img/telegram.svg
  src/routes/+page.svelte
  src/routes/about/+page.svelte
  static/welcomePicture.jpg
Labels: Feature

#51 ✅ 🐛 fix: make checkboxed on Home page uncheckable
  src/routes/+page.svelte
Labels: Fix

#52 📝 feat: update documentation with badges
  README.md
Labels: Docs

#54 Feat/about page
  src/lib/components/Navbar.svelte
  src/lib/components/Team.svelte
  src/lib/components/TechnologicalStack.svelte
  src/lib/components/Welcome.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/about/+page.svelte
  static/logo_small.svg
Labels: Feature

#63 :sparkles: feat: fixed redirection between Home, Login, and Transactions pages
  src/lib/components/LoginForm.svelte
  src/routes/+page.svelte
Labels: Feature

#66 :lipstick: feat: solved issue in duplicated elements in user input
  src/lib/components/AddTransaction.svelte
Labels: Feature

#67 ✨ feat: design and redirecting between pages
  src/lib/components/Transaction.svelte
  src/routes/+page.svelte
  src/routes/transactions/+page.svelte
Labels: Feature

#69 📝 feat: add badges in README.md
  README.md
Labels: Docs

#70 🩹 fix: checbox unclickable
  src/routes/+page.svelte
Labels: Fix
